# This Porter configuration uses limited CNAB parameters and instead relies on
# an existing Ansible inventory for configuration management

name: ElasticstackAzure
version: 0.2.0
description: "An Elasticstack Porter configuration"
invocationImage: cnabquickstarts.azurecr.io/porter/elasticstack-azure:0.2.0
tag: cnabquickstarts.azurecr.io/porter/elasticstack-azure/bundle:0.2.0
dockerfile: Dockerfile.tmpl

mixins:
  - exec

credentials:
  # put the SSH key for accessing the VMs in the default location so we don't need send Ansible extra arguments
  # NOTE: this will need its file permissions fixed inside the invocation image
  - name: ssh_private_key
    path: /root/.ssh/id_rsa
  # ensure the standard enviroment variables for Azure SPN auth are injected into the image
  - name: azure_subscription_id
    env: AZURE_SUBSCRIPTION_ID
  - name: azure_client_id
    env: AZURE_CLIENT_ID
  - name: azure_secret
    env: AZURE_SECRET
  - name: azure_tenant
    env: AZURE_TENANT

parameters:
  # this value relates to an Ansible 'environment'
  - name: environment_name
    type: string
  # this value allows the SSH public key to be easily overriden when using a custom 'ssh_private_key'
  - name: ssh_public_key
    type: string
    # replicate the default value from the Ansible playbook
    default: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwbhzZV8LoiJoiYSIKbcP8dUdF0ptvyDRZ+BD3claOx599wIIAOK0m/PvlBwa1Mg0oj7+LlTIlxVJQfq2i1/i6qADalzdKWikLWcAALEgVxMfXbHty1NL2KZfW8QQkj2+kqg/+1tDLmA2xwXcoW2kodUYEwo3Ldl60ZgRSldWvs1H8nmY9qUqvpO/XIFAnPv+qtDZNurmO+I2z6hwpozeYLeVpIvpU0cuyjJIAfnu9mJzhHNC+H8mS1n73VtPh2EAaxRgWeHA9HxJqOLQ/r3AwOYjk6JL2UYTSzI7oeoK1LV1773/FkjlV3BHOwzD/8G/o8syxk9+c84cg8I6aQKp1 esadmin"

install:
  - exec:
      description: "Fix the file permissions of the injected SSH key"
      command: /bin/bash
      flags:
        c: chmod 600 /root/.ssh/id_rsa
  - exec:
      description: "Run installation playbook"
      command: ansible-playbook
      arguments:
        - ansible/install.yml
      flags:
        i: ansible/environments/{{ bundle.parameters.environment_name }}
        e:
          - admin_public_key="{{ bundle.parameters.ssh_public_key }}"
        # uncomment for more logging
        # v:


upgrade:
  - exec:
      description: "Fix the file permissions of the injected SSH key"
      command: /bin/bash
      flags:
        c: chmod 600 /root/.ssh/id_rsa
  - exec:
      description: "Run installation playbook (upgrade)"
      command: ansible-playbook
      arguments:
        - ansible/install.yml
      flags:
        i: ansible/environments/{{ bundle.parameters.environment_name }}
        e:
          - skip_provision=true
        # uncomment for more logging
        # v:          

uninstall:
  - exec:
      description: "Run uninstallation playbook"
      command: ansible-playbook
      arguments:
        - ansible/uninstall.yml
      flags:
        i: ansible/environments/{{ bundle.parameters.environment_name }}
        # uncomment for more logging
        # v:
