kind: Service
apiVersion: v1
metadata:
  name: calculator-front-end
  labels:
    app: calculator-front-end
spec:
  selector:
    app: calculator-front-end
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: calculator-front-end-ingress
  labels:
    app: calculator-front-end
spec:
  rules:
  - http:
      paths:
        - path: /
          backend:
            serviceName: calculator-front-end
            servicePort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-front-end
  labels:
    app: calculator-front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator-front-end
  template:
    metadata:
      labels:
        app: calculator-front-end
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "calculator-front-end"
        dapr.io/port: "8080"
    spec:
      containers:
      - name: calculator-front-end
        image: '{{ .Values.reactCalculator.image.repository }}:{{ .Values.reactCalculator.image.tag }}'
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
