FROM debian:stretch

ARG BUNDLE_DIR

ENV KUBEFLOW_REPO=https://github.com/kubeflow/kubeflow
ENV KUBEFLOW_VERSION=v0.7.0-rc.8
ENV TOOLHOME="/usr/bin"

COPY . $BUNDLE_DIR

RUN apt-get update && apt-get -y install wget
RUN wget ${KUBEFLOW_REPO}/releases/download/${KUBEFLOW_VERSION}/kfctl_${KUBEFLOW_VERSION}_linux.tar.gz
RUN tar -xvf kfctl_${KUBEFLOW_VERSION}_linux.tar.gz -C ${TOOLHOME} && chmod +x "${TOOLHOME}/kfctl"
