---
# file: roles/elasticsearch/tasks/install.yml

- name: Add Elasticsearch apt-key
  apt_key: 
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  become: true

- name: Add Elasticsearch apt repository
  apt_repository: 
    repo: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main' 
    state: present 
    update_cache: yes
  become: true
  # add retry in case apt is already locked due to initial VM provisioning tasks
  retries: 12
  delay: 10

- name: Install required packages
  apt:
    name:
      - elasticsearch
    update_cache: no
  become: true

- name: Python pip installed?
  command: pip --version
  ignore_errors: yes
  changed_when: false
  register: check_pip

- name: Download pip bootstrapper
  get_url:
    url: https://github.com/pypa/get-pip/blob/master/get-pip.py?raw=true
    dest: /tmp/get-pip.py
    mode: 755
  when: check_pip.rc != 0
  register: pip_bootstrapper_files
    
- name: Install pip
  command: "{{ pip_bootstrapper_files.dest }}"
  when: check_pip.rc != 0
  become: true

- name: Install pyOpenSSL
  pip:
    name: pyopenssl
    executable: pip
  become: true
