FROM continuumio/miniconda3

ARG BUNDLE_DIR

# PORTER_MIXINS

RUN az extension add --name azure-cli-ml

ENV KUBEFLOW_REPO=https://github.com/kubeflow/kubeflow
ENV KUBEFLOW_VERSION=v0.7.0
ENV TOOLHOME="/usr/bin"

RUN apt-get update && apt-get -y install wget bzip2

RUN wget ${KUBEFLOW_REPO}/releases/download/${KUBEFLOW_VERSION}/kfctl_${KUBEFLOW_VERSION}_linux.tar.gz
RUN tar -xvf kfctl_${KUBEFLOW_VERSION}_linux.tar.gz -C ${TOOLHOME} && chmod +x "${TOOLHOME}/kfctl"

RUN pip install https://storage.googleapis.com/ml-pipeline/release/latest/kfp.tar.gz --upgrade

COPY . $BUNDLE_DIR