name: Quickstart CI

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build-and-publish:
    if: "!contains(github.event.head_commit.message, '***NO_CI***')"
    name: Build & Publish
    runs-on: ubuntu-latest
    env:
      RUN_PUBLISH_STEPS: ${{ secrets.REGISTRY_SERVER != '' && secrets.REGISTRY_USERNAME != '' && secrets.REGISTRY_PASSWORD != '' && secrets.GITHUB_TOKEN != '' }}
    steps:
      - name: '[DEBUG] Echo environment variables'
        run: 'gci Env:'
        shell: pwsh

      - name: Checkout Repo
        uses: actions/checkout@v1.1.0

      - name: '[WORKAROUND] Fetch required tags for GitVersion'
        run: |
          git fetch --tags
          git branch --create-reflog master origin/master

      - name: '[WORKAROUND] Get branch name'
        id: get_branch_name
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/get-branch-name@v1

      - name: Calculate quickstart solution version from Porter manifest, using GitVersion
        id: calculate_version
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/calculate-version@v1
        with:
          manifest_path: porter/airflow/porter.yaml
          branch: ${{ steps.get_branch_name.outputs.branch_name }}

      - name: Install latest version of Porter and mixins
        id: install_porter
        uses: deislabs/porter-gh-action@master
    
      - name: Install Porter mixins from manifest
        id: install_porter_mixins
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/install-porter-mixins@v1
        with:
          manifest_path: porter/airflow/porter.yaml

      - name: Patch version and registry for bundle and invocation image
        id: replace_version_and_registry
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/replace-version-and-registry@v1
        with:
          manifest_path: porter/airflow/porter.yaml
          version: ${{ steps.calculate_version.outputs.version }}
          tag: ${{ steps.calculate_version.outputs.version }}
          registry: ${{ secrets.REGISTRY_SERVER || 'gurpreet.azurecr.io' }}

      - name: Build Porter bundle
        id: build_porter_bundle
        run: porter build
        working-directory: porter/airflow

      - name: Publish Porter bundle and invocation image
        id: publish_porter_bundle
        run: porter publish
        working-directory: porter/airflow

      - name: Patch bundle and invocation image tags with 'latest'
        id: replace_tag_with_latest
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/replace-version-and-registry@v1
        with:
          manifest_path: porter/airflow/porter.yaml
          version: ${{ steps.calculate_version.outputs.version }}
          tag: 'latest'
          registry: ${{ secrets.REGISTRY_SERVER || 'gurpreet.azurecr.io' }}
