name: Quickstart CI

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build-and-publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: '[DEBUG] Echo environment variables'
        run: 'gci Env:'
        shell: pwsh

      - name: Checkout Repo
        uses: actions/checkout@v1.1.0

      - name: Read params.ini
        id: params
        run: |
          . params.ini
          'echo "Registry server: $REGISTRY_SERVER"'
          ::set-output name=registry_server::$REGISTRY_SERVER

      - name: '[WORKAROUND] Fetch required tags for GitVersion'
        run: |
          git fetch --tags
          git branch --create-reflog master origin/master

      - name: '[WORKAROUND] Get branch name'
        id: get_branch_name
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/get-branch-name@v1

      - name: Validate & detect quickstart solution changes
        id: validate_and_detect_qs_changes
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/validate-and-detect-quickstart-changes@v1
        with:
          repo_name: ${{ github.repository }}
          trigger: ${{ github.event_name }}
          pr_number: ${{ github.event.number }}
          source_version: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true'
        name: Authenticate against Azure Container Registry (docker registry)
        uses: azure/container-actions/docker-login@master
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          login-server: ${{ steps.params.outputs.registry_server }}
      
      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true' && steps.validate_and_detect_qs_changes.outputs.quickstart_tool == 'porter'
        name: Calculate quickstart solution version from Porter manifest, using GitVersion
        id: calculate_version
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/calculate-version@v1
        with:
          manifest_path: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/porter.yaml
          branch: ${{ steps.get_branch_name.outputs.branch_name }}

      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true' && steps.validate_and_detect_qs_changes.outputs.quickstart_tool == 'porter'
        name: Detect Porter mixins from manifest
        id: detect_porter_mixins
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/detect-porter-mixins@v1
        with:
          manifest_path: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/porter.yaml

      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true' && steps.validate_and_detect_qs_changes.outputs.quickstart_tool == 'porter'
        name: Install latest version of Porter and mixins
        id: install_porter
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/install-porter@v1
        with:
          porter_version: latest
          mixins: ${{ steps.detect_porter_mixins.outputs.mixins }}

      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true' && steps.validate_and_detect_qs_changes.outputs.quickstart_tool == 'porter'
        name: Patch version and registry for bundle and invocation image
        id: replace_version_and_registry
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/replace-version-and-registry@v1
        with:
          manifest_path: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/porter.yaml
          version: ${{ steps.calculate_version.outputs.version }}
          tag: ${{ steps.calculate_version.outputs.version }}
          registry: ${{ steps.params.outputs.registry_server }}

      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true' && steps.validate_and_detect_qs_changes.outputs.quickstart_tool == 'porter'
        name: Build Porter bundle
        id: build_porter_bundle
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/build-porter-bundle@v1
        with:
          bundle_dir: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}

      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true' && steps.validate_and_detect_qs_changes.outputs.quickstart_tool == 'porter'
        name: Publish Porter bundle and invocation image
        id: publish_porter_bundle
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/publish-porter-bundle@v1
        with:
          bundle_dir: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}

      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true' && steps.validate_and_detect_qs_changes.outputs.quickstart_tool == 'porter' && github.event_name == 'push'
        name: Patch bundle and invocation image tags with 'latest'
        id: replace_tag_with_latest
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/replace-version-and-registry@v1
        with:
          manifest_path: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/porter.yaml
          version: ${{ steps.calculate_version.outputs.version }}
          tag: 'latest'
          registry: ${{ steps.params.outputs.registry_server }}

      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true' && steps.validate_and_detect_qs_changes.outputs.quickstart_tool == 'porter' && github.event_name == 'push'
        name: Publish 'latest' Porter bundle and invocation image
        id: publish_latest_porter_bundle
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/publish-porter-bundle@v1
        with:
          bundle_dir: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}
          
      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true'
        name: Generate simple ARM template for 'Deploy to Azure' button
        id: generate_simple_arm_template
        uses: endjin/CNAB.ARM-Converter.GitHub.Actions/run-cnab-to-arm-tool@v1
        with:
          bundle_path: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/.cnab/bundle.json
          output_path: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/azuredeploy-simple.json
          simplify: true

      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true'
        name: Generate advanced ARM template for 'Deploy to Azure' button
        id: generate_advanced_arm_template
        uses: endjin/CNAB.ARM-Converter.GitHub.Actions/run-cnab-to-arm-tool@v1
        with:
          bundle_path: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/.cnab/bundle.json
          output_path: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/azuredeploy-advanced.json
          simplify: false
          
      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true'
        name: Generate quickstart solution readme
        id: generate_readme
        uses: endjin/CNAB.ARM-Converter.GitHub.Actions/generate-readme@v1
        with:
          bundle_metadata_path: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/.cnab/bundle.json
          instructions_path: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/INSTRUCTIONS.md
          simple_template_uri: https://raw.githubusercontent.com/${{ github.repository }}/${{ steps.get_branch_name.outputs.branch_name }}/${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/azuredeploy-simple.json
          advanced_template_uri: https://raw.githubusercontent.com/${{ github.repository }}/${{ steps.get_branch_name.outputs.branch_name }}/${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/azuredeploy-advanced.json
          output_path: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/README.md

      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true'
        name: Commit & push ARM template & readme (if updated)
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/git-commit-updates@v1
        with:
          add_path_spec: '${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/README.md ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/azuredeploy-simple.json ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/azuredeploy-advanced.json'
          commit_message: "Update ARM template / readme for bundle '${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}'"
          branch: ${{ steps.get_branch_name.outputs.branch_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
